import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-purple-100 text-black border-b border-black px-4 py-3 text-sm font-medium text-center">
          We&apos;re a permissionless prediction markets platform operating on MONAD testnet. We hope to see a lot of changes in the upcoming days, if you wish to contribute to the project or help it get on the mainnet please contact <a href="https://twitter.com/prathamkode" target="_blank" rel="noopener noreferrer" className="underline hover:text-purple-700">@prathamkode</a>. We hope you enjoy!
        </div>
        {children}
      </body>
    </html>
  );
}
